name: Build and Push Docker Image for Helm Client

on:
  push:
    branches:
      - main
      - develop
      - 'v*.*.*'
  pull_request:

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Docker tag
        id: docker_tag
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
            echo "push=true" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
            echo "tag=dev-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
            echo "push=true" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
            echo "push=true" >> $GITHUB_OUTPUT
          else
            echo "push=false" >> $GITHUB_OUTPUT
          fi

      # ARM support
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: steps.docker_tag.outputs.push == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: ${{ steps.docker_tag.outputs.push }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_REPO }}/helm-client:${{ steps.docker_tag.outputs.tag }}

      - name: Update Docker Hub description
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_REPO }}/helm-client
